[package]
name = "rosetta-mq"
authors = ["Jordan Baxter"]
description = "A general purpose MQTT decoding tool for debugging MQTT based applications."
repository = "https://github.com/baxterjo/rosetta-mq"
readme = "README.md"
keywords = ["mqtt", "iot", "protobuf"]
categories = ["command-line-utilities", "encoding", "network-programming"]
version = "0.0.1"
edition = "2024"
license = "MIT OR Apache-2.0"
rust-version = "1.85.1"

[lib]
name = "rosetta_mq"
path = "src/lib.rs"

[[bin]]
name = "rosetta-mq"
path = "src/main.rs"
required-features = ["cli"]

[features]
default = ["cli"]
cli = ["dep:clap", "dep:tracing-subscriber", "dep:anyhow"]

[dependencies]
tokio = { version = "1", features = [
  "rt-multi-thread",
  "macros",
  "sync",
  "signal",
  "time",
] }
rumqttc = { version = "0.25", features = ["websocket"] }
serde = { version = "1", features = ["derive"] }
toml = "1"
thiserror = "2"
tracing = "0.1"
hex = "0.4"
bytes = "1"
rustls-pemfile = "2"
rustls-native-certs = "0.8"
prost-reflect = { version = "0.16", features = ["serde"] }
protox = "0.9"
serde_json = "1"
clap = { version = "4", features = ["derive"], optional = true }
tracing-subscriber = { version = "0.3", features = [
  "env-filter",
], optional = true }
anyhow = { version = "1", optional = true }

[dev-dependencies]
rumqttd = { version = "0.19", features = ["verify-client-cert"] }
prost = "0.14"
tempdir = "0.3.7"
rcgen = "0.14.8"
time = "0.3.54"
