use std::collections::HashMap;
use std::net::SocketAddr;
use std::path::{Path, PathBuf};
use std::time::Duration;

use rumqttc::QoS;
use tokio::time::timeout;

use rosetta_mq::auth::{AuthConfig, MtlsConfig, PasswordSource, UserPassConfig};
use rosetta_mq::client::Client;
use rosetta_mq::config::BrokerConfig;

const MTLS_TEST_PORT: u16 = 18885;
const USERPASS_TEST_PORT: u16 = 18886;

// Generated by `cargo run --example dev_generate_test_certs` -- a CA plus a server cert (SAN
// 127.0.0.1) and client cert, both signed by it. Test-only fixtures, never used in production.
const TLS_FIXTURES_DIR: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures/tls");

fn tls_fixture(name: &str) -> PathBuf {
    Path::new(TLS_FIXTURES_DIR).join(name)
}

fn rumqttd_config(
    port: u16,
    tls: Option<rumqttd::TlsConfig>,
    auth: Option<HashMap<String, String>>,
) -> rumqttd::Config {
    let listen: SocketAddr = format!("127.0.0.1:{port}").parse().unwrap();

    let mut v4 = HashMap::new();
    v4.insert(
        "test".to_string(),
        rumqttd::ServerSettings {
            name: "test".to_string(),
            listen,
            tls,
            next_connection_delay_ms: 1,
            connections: rumqttd::ConnectionSettings {
                connection_timeout_ms: 5000,
                max_payload_size: 20 * 1024,
                max_inflight_count: 100,
                auth,
                external_auth: None,
                dynamic_filters: false,
            },
        },
    );

    rumqttd::Config {
        id: 0,
        router: rumqttd::RouterConfig {
            max_connections: 10,
            max_outgoing_packet_count: 200,
            max_segment_size: 1024 * 1024,
            max_segment_count: 10,
            ..Default::default()
        },
        v4: Some(v4),
        v5: None,
        ws: None,
        cluster: None,
        console: None,
        bridge: None,
        prometheus: None,
        metrics: None,
    }
}

async fn wait_for_port(port: u16) {
    let addr = format!("127.0.0.1:{port}");
    let deadline = tokio::time::Instant::now() + Duration::from_secs(5);
    loop {
        if tokio::net::TcpStream::connect(&addr).await.is_ok() {
            return;
        }
        assert!(
            tokio::time::Instant::now() < deadline,
            "broker did not start listening on {addr} in time"
        );
        tokio::time::sleep(Duration::from_millis(50)).await;
    }
}

/// Proves an authenticated connection is actually usable, not just that `Client::connect`
/// returned without panicking (which it always does -- `connect` is infallible and only reports
/// connection failures asynchronously through the driver task). Subscribing and then seeing our
/// own publish come back only happens if the broker accepted the connection *and* the session
/// past that point works normally.
async fn assert_connection_round_trips(conn: &rosetta_mq::client::MqttConnection) {
    Client::subscribe_all(&conn.client, ["test/echo"])
        .await
        .unwrap();
    // Give the broker time to ack the subscription before publishing.
    tokio::time::sleep(Duration::from_millis(300)).await;

    conn.client
        .publish("test/echo", QoS::AtLeastOnce, false, "ping")
        .await
        .unwrap();
}

#[tokio::test]
async fn mtls_auth_connects_and_round_trips() {
    let tls = rumqttd::TlsConfig::Rustls {
        capath: Some(tls_fixture("ca.pem").to_string_lossy().into_owned()),
        certpath: tls_fixture("server-cert.pem")
            .to_string_lossy()
            .into_owned(),
        keypath: tls_fixture("server-key.pem").to_string_lossy().into_owned(),
    };
    let broker_config = rumqttd_config(MTLS_TEST_PORT, Some(tls), None);
    std::thread::spawn(move || {
        let mut broker = rumqttd::Broker::new(broker_config);
        let _ = broker.start();
    });
    wait_for_port(MTLS_TEST_PORT).await;

    let broker = BrokerConfig {
        host: "127.0.0.1".to_string(),
        port: MTLS_TEST_PORT,
        client_id: "rosetta-mq-mtls-test".to_string(),
        auth: None,
    };
    let auth_config = AuthConfig::Mtls(MtlsConfig {
        ca_file: tls_fixture("ca.pem"),
        cert_file: tls_fixture("client-cert.pem"),
        key_file: tls_fixture("client-key.pem"),
    });
    let resolved_auth = auth_config.build(Path::new(".")).unwrap();

    let mut conn = Client::connect(&broker, &resolved_auth);
    assert_connection_round_trips(&conn).await;

    let publish = timeout(Duration::from_secs(5), conn.incoming.recv())
        .await
        .expect("timed out waiting for echoed publish over mTLS")
        .expect("channel closed");
    assert_eq!(publish.topic, "test/echo");
    assert_eq!(publish.payload, "ping");
}

#[tokio::test]
async fn userpass_auth_connects_and_round_trips() {
    let auth = HashMap::from([("device-reader".to_string(), "supersecret".to_string())]);
    let broker_config = rumqttd_config(USERPASS_TEST_PORT, None, Some(auth));
    std::thread::spawn(move || {
        let mut broker = rumqttd::Broker::new(broker_config);
        let _ = broker.start();
    });
    wait_for_port(USERPASS_TEST_PORT).await;

    let broker = BrokerConfig {
        host: "127.0.0.1".to_string(),
        port: USERPASS_TEST_PORT,
        client_id: "rosetta-mq-userpass-test".to_string(),
        auth: None,
    };
    let auth_config = AuthConfig::UserPass(UserPassConfig {
        username: "device-reader".to_string(),
        password: PasswordSource::Literal("supersecret".to_string()),
    });
    let resolved_auth = auth_config.build(Path::new(".")).unwrap();

    let mut conn = Client::connect(&broker, &resolved_auth);
    assert_connection_round_trips(&conn).await;

    let publish = timeout(Duration::from_secs(5), conn.incoming.recv())
        .await
        .expect("timed out waiting for echoed publish over userpass auth")
        .expect("channel closed");
    assert_eq!(publish.topic, "test/echo");
    assert_eq!(publish.payload, "ping");
}
